// Package mcpserver 将 grok 搜索能力注册为 MCP 工具（grok_web_search、grok_x_search）。
package mcpserver

import (
	"context"
	"fmt"
	"strings"

	"github.com/grok-mcp/internal/grok"
	"github.com/grok-mcp/internal/logx"
	"github.com/modelcontextprotocol/go-sdk/mcp"
)

const (
	webSearchToolName        = "grok_web_search"
	webSearchToolTitle       = "Grok Web Search"
	webSearchToolDescription = "Search the public web in real time via Grok web_search " +
		"(through CPA /v1/responses). Use for fresh public web information and " +
		"source-backed answers. query is required; model is optional and defaults " +
		"to GROK_MODEL; allowed_domains and excluded_domains are mutually " +
		"exclusive with a maximum of 5 domains each. enable_image_understanding " +
		"and enable_image_search apply to this web search tool."

	xSearchToolName        = "grok_x_search"
	xSearchToolTitle       = "Grok X Search"
	xSearchToolDescription = "Search posts on X in real time via Grok x_search " +
		"(through CPA /v1/responses). Use for current X/Twitter posts and " +
		"source-backed answers. query is required; model is optional and defaults " +
		"to GROK_MODEL. This tool accepts only query and model; domain filters " +
		"and image-related options belong to grok_web_search."
)

// WebSearchInput 为 grok_web_search 的 JSON 入参，字段名与 jsonschema 标签供客户端生成表单。
type WebSearchInput struct {
	Query                    string   `json:"query" jsonschema:"Search query text"`
	Model                    string   `json:"model,omitempty" jsonschema:"Optional model override. Defaults to GROK_MODEL env var."`
	AllowedDomains           []string `json:"allowed_domains,omitempty" jsonschema:"Only search within these domains (max 5). Cannot be used with excluded_domains."`
	ExcludedDomains          []string `json:"excluded_domains,omitempty" jsonschema:"Exclude these domains from search (max 5). Cannot be used with allowed_domains."`
	EnableImageUnderstanding *bool    `json:"enable_image_understanding,omitempty" jsonschema:"Enable image understanding during web search (web_search only)."`
	EnableImageSearch        *bool    `json:"enable_image_search,omitempty" jsonschema:"Enable image search results in web search answers (web_search only)."`
}

// XSearchInput 为 grok_x_search 的 JSON 入参。X 搜索不暴露 web_search 专属的域名或图片选项。
type XSearchInput struct {
	Query string `json:"query" jsonschema:"Search query text"`
	Model string `json:"model,omitempty" jsonschema:"Optional model override. Defaults to GROK_MODEL env var."`
}

// SearchOutput 为工具成功时的结构化返回，会序列化为 MCP 工具结果 JSON。
// 失败时返回零值 SearchOutput（各字段为零值），由 toolError 单独承载错误文案。
type SearchOutput struct {
	Answer    string        `json:"answer,omitempty" jsonschema:"Search answer generated by Grok"`
	Citations []string      `json:"citations,omitempty" jsonschema:"Source URLs cited in the answer"`
	Sources   []grok.Source `json:"sources,omitempty" jsonschema:"Source references with optional titles"`
	Usage     *grok.Usage   `json:"usage,omitempty" jsonschema:"Token usage reported by upstream"`
}

// RegisterTools 在 MCP Server 上注册网页搜索与 X 搜索两个工具。
func RegisterTools(server *mcp.Server, client *grok.Client, debug bool) {
	log := logx.New("mcp", debug)
	registerWebSearchTool(server, client, log)
	registerXSearchTool(server, client, log)
}

func registerWebSearchTool(server *mcp.Server, client *grok.Client, log *logx.Logger) {
	mcp.AddTool(server, newSearchTool(webSearchToolName, webSearchToolTitle, webSearchToolDescription), func(ctx context.Context, req *mcp.CallToolRequest, input WebSearchInput) (*mcp.CallToolResult, SearchOutput, error) {
		searchReq := grok.SearchRequest{
			Query:                    input.Query,
			Model:                    input.Model,
			ToolType:                 grok.ToolTypeWebSearch,
			AllowedDomains:           input.AllowedDomains,
			ExcludedDomains:          input.ExcludedDomains,
			EnableImageUnderstanding: input.EnableImageUnderstanding,
			EnableImageSearch:        input.EnableImageSearch,
		}
		return runSearch(ctx, req, client, log, searchReq)
	})
}

func registerXSearchTool(server *mcp.Server, client *grok.Client, log *logx.Logger) {
	mcp.AddTool(server, newSearchTool(xSearchToolName, xSearchToolTitle, xSearchToolDescription), func(ctx context.Context, req *mcp.CallToolRequest, input XSearchInput) (*mcp.CallToolResult, SearchOutput, error) {
		searchReq := grok.SearchRequest{
			Query:    input.Query,
			Model:    input.Model,
			ToolType: grok.ToolTypeXSearch,
		}
		return runSearch(ctx, req, client, log, searchReq)
	})
}

func newSearchTool(name, title, description string) *mcp.Tool {
	openWorldHint := true
	return &mcp.Tool{
		Name:        name,
		Title:       title,
		Description: description,
		Annotations: &mcp.ToolAnnotations{
			ReadOnlyHint:  true,
			OpenWorldHint: &openWorldHint,
		},
	}
}

// runSearch 调用上游流式搜索，并在客户端提供 progressToken 时推送每轮搜索进度通知。
func runSearch(ctx context.Context, req *mcp.CallToolRequest, client *grok.Client, log *logx.Logger, searchReq grok.SearchRequest) (*mcp.CallToolResult, SearchOutput, error) {
	query := strings.TrimSpace(searchReq.Query)
	if query == "" {
		return toolError("query is required"), SearchOutput{}, nil
	}
	searchReq.Query = query
	searchReq.Model = strings.TrimSpace(searchReq.Model)
	toolType := searchReq.ToolType

	var progress float64
	var token any
	if req != nil {
		token = req.Params.GetProgressToken()
	}

	log.Debugf("search start tool=%s query=%q", toolType, logx.Truncate(query, 80))
	result, err := client.SearchStream(ctx, searchReq, func(round grok.SearchRound) {
		if token == nil || req == nil {
			return
		}
		progress++
		_ = req.Session.NotifyProgress(ctx, &mcp.ProgressNotificationParams{
			ProgressToken: token,
			Progress:      progress,
			// Grok search has no fixed total round count. Set Total to the current
			// progress so clients show "x/x" instead of an unknown-total "x/?".
			Total:   progress,
			Message: formatSearchRoundMessage(round),
		})
	})
	if err != nil {
		log.Debugf("search failed tool=%s: %v", toolType, err)
		return toolError(classifySearchError(err)), SearchOutput{}, nil
	}

	log.Debugf("search done tool=%s citations=%d sources=%d", toolType, len(result.Citations), len(result.Sources))
	output := SearchOutput{
		Answer:    result.Answer,
		Citations: result.Citations,
		Sources:   result.Sources,
		Usage:     result.Usage,
	}
	return nil, output, nil
}

// formatSearchRoundMessage 将上游搜索轮次格式化为面向终端用户的进度文案。
func formatSearchRoundMessage(round grok.SearchRound) string {
	if q := strings.TrimSpace(round.Query); q != "" {
		return fmt.Sprintf("🔍 第%d轮：搜索 \"%s\"", round.Round, q)
	}
	if u := strings.TrimSpace(round.URL); u != "" {
		return fmt.Sprintf("📄 第%d轮：读取 %s", round.Round, u)
	}
	return fmt.Sprintf("🔍 第%d轮：搜索中", round.Round)
}

// toolError 构造 MCP 约定的 IsError 工具结果（不向 Go error 传播，避免断开会话）。
func toolError(message string) *mcp.CallToolResult {
	return &mcp.CallToolResult{
		IsError: true,
		Content: []mcp.Content{&mcp.TextContent{Text: message}},
	}
}

// classifySearchError 把上游/网络错误映射为面向 MCP 客户端的简短文案，
// 不泄露上游 body 细节（可能含 CPA 内部信息），但区分类别便于客户端处理。
func classifySearchError(err error) string {
	if err == nil {
		return "search request failed"
	}
	msg := err.Error()
	switch {
	case strings.Contains(msg, "context deadline exceeded"), strings.Contains(msg, "timeout"):
		return "upstream search timed out"
	case strings.Contains(msg, "upstream returned HTTP"):
		// 提取状态码片段供客户端区分 4xx/5xx，不附带 body。
		return strings.TrimSpace(strings.SplitN(msg, ":", 2)[0])
	case strings.Contains(msg, "did not contain answer text"):
		return "upstream returned empty answer"
	case strings.Contains(msg, "ended without response.completed"):
		return "upstream stream ended prematurely"
	case strings.Contains(msg, "upstream stream error"):
		return "upstream stream error"
	default:
		return "search request failed"
	}
}
