package mcpserver

import (
	"context"
	"fmt"
	"log"
	"os"
	"strings"

	"github.com/grok-mcp/internal/grok"
	"github.com/modelcontextprotocol/go-sdk/mcp"
)

type SearchInput struct {
	Query                    string   `json:"query" jsonschema:"Search query text"`
	Model                    string   `json:"model,omitempty" jsonschema:"Optional model override. Defaults to GROK_MODEL env var."`
	AllowedDomains           []string `json:"allowed_domains,omitempty" jsonschema:"Only search within these domains (max 5). Cannot be used with excluded_domains."`
	ExcludedDomains          []string `json:"excluded_domains,omitempty" jsonschema:"Exclude these domains from search (max 5). Cannot be used with allowed_domains."`
	EnableImageUnderstanding *bool    `json:"enable_image_understanding,omitempty" jsonschema:"Enable image understanding during web search (web_search only)."`
	EnableImageSearch        *bool    `json:"enable_image_search,omitempty" jsonschema:"Enable image search results in web search answers (web_search only)."`
}

type SearchOutput struct {
	Answer    string        `json:"answer" jsonschema:"Search answer generated by Grok"`
	Citations []string      `json:"citations" jsonschema:"Source URLs cited in the answer"`
	Sources   []grok.Source `json:"sources" jsonschema:"Source references with optional titles"`
	Usage     *grok.Usage   `json:"usage,omitempty" jsonschema:"Token usage reported by upstream"`
}

func RegisterTools(server *mcp.Server, client *grok.Client) {
	mcp.AddTool(server, &mcp.Tool{
		Name:        "grok_web_search",
		Description: "Search the public web in real time via Grok (through CPA /v1/responses + web_search tool). Returns an answer with source URLs.",
	}, func(ctx context.Context, req *mcp.CallToolRequest, input SearchInput) (*mcp.CallToolResult, SearchOutput, error) {
		return runSearch(ctx, req, client, grok.ToolTypeWebSearch, input)
	})

	mcp.AddTool(server, &mcp.Tool{
		Name:        "grok_x_search",
		Description: "Search posts on X in real time via Grok (through CPA /v1/responses + x_search tool). Returns an answer with source URLs.",
	}, func(ctx context.Context, req *mcp.CallToolRequest, input SearchInput) (*mcp.CallToolResult, SearchOutput, error) {
		return runSearch(ctx, req, client, grok.ToolTypeXSearch, input)
	})
}

func runSearch(ctx context.Context, req *mcp.CallToolRequest, client *grok.Client, toolType grok.ToolType, input SearchInput) (*mcp.CallToolResult, SearchOutput, error) {
	query := strings.TrimSpace(input.Query)
	if query == "" {
		return toolError("query is required"), SearchOutput{}, nil
	}

	searchReq := grok.SearchRequest{
		Query:                    query,
		Model:                    strings.TrimSpace(input.Model),
		ToolType:                 toolType,
		AllowedDomains:           input.AllowedDomains,
		ExcludedDomains:          input.ExcludedDomains,
		EnableImageUnderstanding: input.EnableImageUnderstanding,
		EnableImageSearch:        input.EnableImageSearch,
	}

	var progress float64
	var token any
	if req != nil {
		token = req.Params.GetProgressToken()
	}

	debugf("search start tool=%s query=%q", toolType, truncateQuery(query, 80))
	result, err := client.SearchStream(ctx, searchReq, func(round grok.SearchRound) {
		if token == nil || req == nil {
			return
		}
		progress++
		_ = req.Session.NotifyProgress(ctx, &mcp.ProgressNotificationParams{
			ProgressToken: token,
			Progress:      progress,
			Message:       formatSearchRoundMessage(round),
		})
	})
	if err != nil {
		debugf("search failed tool=%s: %v", toolType, err)
		return toolError(err.Error()), SearchOutput{}, nil
	}

	debugf("search done tool=%s citations=%d sources=%d", toolType, len(result.Citations), len(result.Sources))
	output := SearchOutput{
		Answer:    result.Answer,
		Citations: result.Citations,
		Sources:   result.Sources,
		Usage:     result.Usage,
	}
	return nil, output, nil
}

func formatSearchRoundMessage(round grok.SearchRound) string {
	if q := strings.TrimSpace(round.Query); q != "" {
		return fmt.Sprintf("🔍 第%d轮：搜索 \"%s\"", round.Round, q)
	}
	if u := strings.TrimSpace(round.URL); u != "" {
		return fmt.Sprintf("📄 第%d轮：读取 %s", round.Round, u)
	}
	return fmt.Sprintf("🔍 第%d轮：搜索中", round.Round)
}

func toolError(message string) *mcp.CallToolResult {
	return &mcp.CallToolResult{
		IsError: true,
		Content: []mcp.Content{&mcp.TextContent{Text: message}},
	}
}

func debugf(format string, args ...any) {
	if !parseBoolEnv("GROK_MCP_DEBUG") {
		return
	}
	log.SetOutput(os.Stderr)
	log.Printf("[mcp] "+format, args...)
}

func truncateQuery(s string, max int) string {
	if len(s) <= max {
		return s
	}
	return s[:max] + "..."
}

func parseBoolEnv(key string) bool {
	raw := strings.TrimSpace(strings.ToLower(os.Getenv(key)))
	return raw == "1" || raw == "true" || raw == "yes"
}
